using System;
using System.Runtime.CompilerServices;

namespace Recursion.Problems;
/*
You are given string s of length n, having m wildcard characters '?', where each wildcard character represents a single character. 
Write a program which returns a list of all possible distinct strings that can be generated by replacing each wildcard character in s 
with either '0' or '1'.

Any string returned must not contain '?' characters, all must be replaced with either '0' or '1'.

Example One
{
"s": "1?10"
}
Output:

["1010", "1110"]
Example Two
{
"s": "1?0?"
}
Output:

["1000", "1001", "1100", "1101"]
*/
public class StringsWithWildCharachter
{
    public static List<string> Find_all_possibilities(string s) 
    {
        // Write your code here.
        var result = new List<string>();
        Helper(s, 0, result, "");
        return result;
    }

    private static void Helper(string s, int currentIndex, List<string> result, string slate)
    {
        if (currentIndex == s.Length)
        {
            result.Add(slate);
            return;
        }
        if(s[currentIndex]=='?')
        {
            Helper(s,currentIndex+1,result,slate+"0");
            Helper(s,currentIndex+1,result,slate+"1");
        }
        else
            Helper(s,currentIndex+1,result,slate+s[currentIndex]);
    }
}
